// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaL_rs07IvfZSDEcSKH8v2WhQFw74mCHw',
    appId: '1:302880035260:web:424f6b05d598cae3ce5bb9',
    messagingSenderId: '302880035260',
    projectId: 'social-media-app-cb150',
    authDomain: 'social-media-app-cb150.firebaseapp.com',
    storageBucket: 'social-media-app-cb150.firebasestorage.app',
    measurementId: 'G-QHPLRW7MX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT22S6uwGa3-llBTOAM-C13ubQXWCHb4M',
    appId: '1:302880035260:android:dd05bdbc82ce917fce5bb9',
    messagingSenderId: '302880035260',
    projectId: 'social-media-app-cb150',
    storageBucket: 'social-media-app-cb150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTMZluV8zZUPLX-nCpFWroWYpLsm5b_k',
    appId: '1:302880035260:ios:4e9d22ca03e2bc97ce5bb9',
    messagingSenderId: '302880035260',
    projectId: 'social-media-app-cb150',
    storageBucket: 'social-media-app-cb150.firebasestorage.app',
    androidClientId: '302880035260-8mgdvv3n080maai6q8ffdp49o7ebep4v.apps.googleusercontent.com',
    iosClientId: '302880035260-sugre5t2mcrtj7mb8ge9mn1t0orghhvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTMZluV8zZUPLX-nCpFWroWYpLsm5b_k',
    appId: '1:302880035260:ios:4e9d22ca03e2bc97ce5bb9',
    messagingSenderId: '302880035260',
    projectId: 'social-media-app-cb150',
    storageBucket: 'social-media-app-cb150.firebasestorage.app',
    androidClientId: '302880035260-8mgdvv3n080maai6q8ffdp49o7ebep4v.apps.googleusercontent.com',
    iosClientId: '302880035260-sugre5t2mcrtj7mb8ge9mn1t0orghhvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaL_rs07IvfZSDEcSKH8v2WhQFw74mCHw',
    appId: '1:302880035260:web:b1d201b0c6c6e705ce5bb9',
    messagingSenderId: '302880035260',
    projectId: 'social-media-app-cb150',
    authDomain: 'social-media-app-cb150.firebaseapp.com',
    storageBucket: 'social-media-app-cb150.firebasestorage.app',
    measurementId: 'G-HNVF49SP13',
  );

}